### ISSUE TITLE
Не выходит корректно из боя

### ISSUE THREAD

**Issue by Studiosis** [denesik/hustle_castle_bot_pack#1]
"capute_mode": 0,
[log.txt](https://github.com/denesik/hustle_castle_bot_pack/files/2805723/log.txt)

**Comment by denesik** [comment]
лог короткий, нужно дольше записывать

**Comment by denesik** [comment]
> "capute_mode": 0,
> [log.txt](https://github.com/denesik/hustle_castle_bot_pack/files/2805723/log.txt)

лог короткий, нужно дольше записывать

**Comment by Studiosis** [comment]
[log.txt](https://github.com/denesik/hustle_castle_bot_pack/files/2816032/log.txt)
Так достаточно? Пропустил фазу выбора
